/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoansIdRouteImport } from './routes/loans.$id'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LoansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/support': typeof SupportRoute
  '/loans/$id': typeof LoansIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/support': typeof SupportRoute
  '/loans/$id': typeof LoansIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/support': typeof SupportRoute
  '/loans/$id': typeof LoansIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/investments' | '/loans' | '/support' | '/loans/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/investments' | '/loans' | '/support' | '/loans/$id'
  id: '__root__' | '/' | '/dashboard' | '/investments' | '/loans' | '/support' | '/loans/$id'
  fileRoutesById: FileRoutesById
}

interface LoansRouteChildren {
  LoansIdRoute: typeof LoansIdRoute
}
const LoansRouteChildren: LoansRouteChildren = {
  LoansIdRoute: LoansIdRoute,
}
const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoansRoute: typeof LoansRouteWithChildren
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof LoansRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoansRoute: LoansRouteWithChildren,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
